id = "selenized"
name = "Selenized"
version = "0.1.0"
schema_version = 1
authors = ["harmtemolder"]
description = "🌓 Selenized color palette — warm aesthetics for machines and people"
repository = "https://github.com/harmtemolder/Solarized.zed"
